site_name: ParNMPC Homepage
repo_url: https://github.com/deng-haoyang/ParNMPC
edit_uri: ""

pages:
- What is ParNMPC: 'index.md'
- Installation: 'installation.md'
- Interfaces: 'interfaces.md'
- Workflow: 'workflow.md'
- Examples:
    - 'Simulation: Semi-active Damper': 'exp_damper.md'
    - 'Simulation: Double Inverted Pendulum on a Cart': 'exp_double_pendulum.md'
    - 'Simulation: Quadrotor': 'exp_quadrotor.md'
    - 'Experiment: Single Inverted Pendulum on a Cart': 'exp_single_pendulum.md'
    - 'Experiment: Helicopter': 'exp_heli.md'
- Tips: 'tips.md'
- About: 'about.md'

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - admonition
  - footnotes
  - codehilite
  
google_analytics:
  - 'UA-120133947-1'
  - 'auto'
  
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'indigo'

